---
development:
  enhance_image_tag: true
  static_image_support: false
test:
  enhance_image_tag: true
  static_image_support: false
staging:
  enhance_image_tag: true
  static_image_support: false
asha:
  enhance_image_tag: true
  static_image_support: true
production:
  enhance_image_tag: true
  static_image_support: true
